//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishingShop.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        public int IdCategory { get; set; }
        public string NameCategory { get; set; }
        public byte[] ImageCategory { get; set; }
    }
}
